// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ByteStringReply_Response int32

const (
	ByteStringReply_SUCCESS ByteStringReply_Response = 0
	ByteStringReply_FAILURE ByteStringReply_Response = 1
	ByteStringReply_ERROR   ByteStringReply_Response = 2
)

var ByteStringReply_Response_name = map[int32]string{
	0: "SUCCESS",
	1: "FAILURE",
	2: "ERROR",
}

var ByteStringReply_Response_value = map[string]int32{
	"SUCCESS": 0,
	"FAILURE": 1,
	"ERROR":   2,
}

func (x ByteStringReply_Response) String() string {
	return proto.EnumName(ByteStringReply_Response_name, int32(x))
}

func (ByteStringReply_Response) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1, 0}
}

type SystemInfoReply_Response int32

const (
	SystemInfoReply_SUCCESS SystemInfoReply_Response = 0
	SystemInfoReply_FAILURE SystemInfoReply_Response = 1
	SystemInfoReply_ERROR   SystemInfoReply_Response = 2
)

var SystemInfoReply_Response_name = map[int32]string{
	0: "SUCCESS",
	1: "FAILURE",
	2: "ERROR",
}

var SystemInfoReply_Response_value = map[string]int32{
	"SUCCESS": 0,
	"FAILURE": 1,
	"ERROR":   2,
}

func (x SystemInfoReply_Response) String() string {
	return proto.EnumName(SystemInfoReply_Response_name, int32(x))
}

func (SystemInfoReply_Response) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{3, 0}
}

type JSONMessageReply_Response int32

const (
	JSONMessageReply_SUCCESS_JSON  JSONMessageReply_Response = 0
	JSONMessageReply_INVALID_PARSE JSONMessageReply_Response = 1
	JSONMessageReply_INVALID_DATA  JSONMessageReply_Response = 2
)

var JSONMessageReply_Response_name = map[int32]string{
	0: "SUCCESS_JSON",
	1: "INVALID_PARSE",
	2: "INVALID_DATA",
}

var JSONMessageReply_Response_value = map[string]int32{
	"SUCCESS_JSON":  0,
	"INVALID_PARSE": 1,
	"INVALID_DATA":  2,
}

func (x JSONMessageReply_Response) String() string {
	return proto.EnumName(JSONMessageReply_Response_name, int32(x))
}

func (JSONMessageReply_Response) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{4, 0}
}

// Request for sending a byte string.
type ByteStringRequest struct {
	ByteString           []byte   `protobuf:"bytes,1,opt,name=ByteString,proto3" json:"ByteString,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ByteStringRequest) Reset()         { *m = ByteStringRequest{} }
func (m *ByteStringRequest) String() string { return proto.CompactTextString(m) }
func (*ByteStringRequest) ProtoMessage()    {}
func (*ByteStringRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *ByteStringRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ByteStringRequest.Unmarshal(m, b)
}
func (m *ByteStringRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ByteStringRequest.Marshal(b, m, deterministic)
}
func (m *ByteStringRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ByteStringRequest.Merge(m, src)
}
func (m *ByteStringRequest) XXX_Size() int {
	return xxx_messageInfo_ByteStringRequest.Size(m)
}
func (m *ByteStringRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ByteStringRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ByteStringRequest proto.InternalMessageInfo

func (m *ByteStringRequest) GetByteString() []byte {
	if m != nil {
		return m.ByteString
	}
	return nil
}

// Response to a byte string.
type ByteStringReply struct {
	Resp                 ByteStringReply_Response `protobuf:"varint,1,opt,name=resp,proto3,enum=api.ByteStringReply_Response" json:"resp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *ByteStringReply) Reset()         { *m = ByteStringReply{} }
func (m *ByteStringReply) String() string { return proto.CompactTextString(m) }
func (*ByteStringReply) ProtoMessage()    {}
func (*ByteStringReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

func (m *ByteStringReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ByteStringReply.Unmarshal(m, b)
}
func (m *ByteStringReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ByteStringReply.Marshal(b, m, deterministic)
}
func (m *ByteStringReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ByteStringReply.Merge(m, src)
}
func (m *ByteStringReply) XXX_Size() int {
	return xxx_messageInfo_ByteStringReply.Size(m)
}
func (m *ByteStringReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ByteStringReply.DiscardUnknown(m)
}

var xxx_messageInfo_ByteStringReply proto.InternalMessageInfo

func (m *ByteStringReply) GetResp() ByteStringReply_Response {
	if m != nil {
		return m.Resp
	}
	return ByteStringReply_SUCCESS
}

// Request with system info payload.
type SystemInfoRequest struct {
	TotalMemory          uint64   `protobuf:"varint,1,opt,name=TotalMemory,proto3" json:"TotalMemory,omitempty"`
	AvailableMemory      uint64   `protobuf:"varint,2,opt,name=AvailableMemory,proto3" json:"AvailableMemory,omitempty"`
	UsedMemory           uint64   `protobuf:"varint,3,opt,name=UsedMemory,proto3" json:"UsedMemory,omitempty"`
	TotalDisk            uint64   `protobuf:"varint,4,opt,name=TotalDisk,proto3" json:"TotalDisk,omitempty"`
	FreeDisk             uint64   `protobuf:"varint,5,opt,name=FreeDisk,proto3" json:"FreeDisk,omitempty"`
	UsedDisk             uint64   `protobuf:"varint,6,opt,name=UsedDisk,proto3" json:"UsedDisk,omitempty"`
	DiskPath             string   `protobuf:"bytes,7,opt,name=DiskPath,proto3" json:"DiskPath,omitempty"`
	Hostname             string   `protobuf:"bytes,8,opt,name=Hostname,proto3" json:"Hostname,omitempty"`
	OS                   string   `protobuf:"bytes,9,opt,name=OS,proto3" json:"OS,omitempty"`
	Timestamp            uint64   `protobuf:"varint,10,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SystemInfoRequest) Reset()         { *m = SystemInfoRequest{} }
func (m *SystemInfoRequest) String() string { return proto.CompactTextString(m) }
func (*SystemInfoRequest) ProtoMessage()    {}
func (*SystemInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{2}
}

func (m *SystemInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SystemInfoRequest.Unmarshal(m, b)
}
func (m *SystemInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SystemInfoRequest.Marshal(b, m, deterministic)
}
func (m *SystemInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SystemInfoRequest.Merge(m, src)
}
func (m *SystemInfoRequest) XXX_Size() int {
	return xxx_messageInfo_SystemInfoRequest.Size(m)
}
func (m *SystemInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SystemInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SystemInfoRequest proto.InternalMessageInfo

func (m *SystemInfoRequest) GetTotalMemory() uint64 {
	if m != nil {
		return m.TotalMemory
	}
	return 0
}

func (m *SystemInfoRequest) GetAvailableMemory() uint64 {
	if m != nil {
		return m.AvailableMemory
	}
	return 0
}

func (m *SystemInfoRequest) GetUsedMemory() uint64 {
	if m != nil {
		return m.UsedMemory
	}
	return 0
}

func (m *SystemInfoRequest) GetTotalDisk() uint64 {
	if m != nil {
		return m.TotalDisk
	}
	return 0
}

func (m *SystemInfoRequest) GetFreeDisk() uint64 {
	if m != nil {
		return m.FreeDisk
	}
	return 0
}

func (m *SystemInfoRequest) GetUsedDisk() uint64 {
	if m != nil {
		return m.UsedDisk
	}
	return 0
}

func (m *SystemInfoRequest) GetDiskPath() string {
	if m != nil {
		return m.DiskPath
	}
	return ""
}

func (m *SystemInfoRequest) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *SystemInfoRequest) GetOS() string {
	if m != nil {
		return m.OS
	}
	return ""
}

func (m *SystemInfoRequest) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

// Response for SystemInfoRequest.
type SystemInfoReply struct {
	Resp                 SystemInfoReply_Response `protobuf:"varint,1,opt,name=resp,proto3,enum=api.SystemInfoReply_Response" json:"resp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *SystemInfoReply) Reset()         { *m = SystemInfoReply{} }
func (m *SystemInfoReply) String() string { return proto.CompactTextString(m) }
func (*SystemInfoReply) ProtoMessage()    {}
func (*SystemInfoReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{3}
}

func (m *SystemInfoReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SystemInfoReply.Unmarshal(m, b)
}
func (m *SystemInfoReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SystemInfoReply.Marshal(b, m, deterministic)
}
func (m *SystemInfoReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SystemInfoReply.Merge(m, src)
}
func (m *SystemInfoReply) XXX_Size() int {
	return xxx_messageInfo_SystemInfoReply.Size(m)
}
func (m *SystemInfoReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SystemInfoReply.DiscardUnknown(m)
}

var xxx_messageInfo_SystemInfoReply proto.InternalMessageInfo

func (m *SystemInfoReply) GetResp() SystemInfoReply_Response {
	if m != nil {
		return m.Resp
	}
	return SystemInfoReply_SUCCESS
}

// Reply to SendJSONMessage()
type JSONMessageReply struct {
	Resp                 JSONMessageReply_Response `protobuf:"varint,1,opt,name=resp,proto3,enum=api.JSONMessageReply_Response" json:"resp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *JSONMessageReply) Reset()         { *m = JSONMessageReply{} }
func (m *JSONMessageReply) String() string { return proto.CompactTextString(m) }
func (*JSONMessageReply) ProtoMessage()    {}
func (*JSONMessageReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{4}
}

func (m *JSONMessageReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JSONMessageReply.Unmarshal(m, b)
}
func (m *JSONMessageReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JSONMessageReply.Marshal(b, m, deterministic)
}
func (m *JSONMessageReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JSONMessageReply.Merge(m, src)
}
func (m *JSONMessageReply) XXX_Size() int {
	return xxx_messageInfo_JSONMessageReply.Size(m)
}
func (m *JSONMessageReply) XXX_DiscardUnknown() {
	xxx_messageInfo_JSONMessageReply.DiscardUnknown(m)
}

var xxx_messageInfo_JSONMessageReply proto.InternalMessageInfo

func (m *JSONMessageReply) GetResp() JSONMessageReply_Response {
	if m != nil {
		return m.Resp
	}
	return JSONMessageReply_SUCCESS_JSON
}

func init() {
	proto.RegisterEnum("api.ByteStringReply_Response", ByteStringReply_Response_name, ByteStringReply_Response_value)
	proto.RegisterEnum("api.SystemInfoReply_Response", SystemInfoReply_Response_name, SystemInfoReply_Response_value)
	proto.RegisterEnum("api.JSONMessageReply_Response", JSONMessageReply_Response_name, JSONMessageReply_Response_value)
	proto.RegisterType((*ByteStringRequest)(nil), "api.ByteStringRequest")
	proto.RegisterType((*ByteStringReply)(nil), "api.ByteStringReply")
	proto.RegisterType((*SystemInfoRequest)(nil), "api.SystemInfoRequest")
	proto.RegisterType((*SystemInfoReply)(nil), "api.SystemInfoReply")
	proto.RegisterType((*JSONMessageReply)(nil), "api.JSONMessageReply")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c) }

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 469 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x53, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0xb5, 0xdd, 0xa4, 0x89, 0x27, 0x21, 0x71, 0x56, 0x80, 0xac, 0x0a, 0xaa, 0xc8, 0xa7, 0x9c,
	0x82, 0x48, 0xcf, 0x48, 0x38, 0x4d, 0x2a, 0x82, 0x9a, 0xa6, 0xda, 0x6d, 0x38, 0x70, 0xa9, 0xb6,
	0xea, 0x10, 0x2c, 0x62, 0x7b, 0xf1, 0x6e, 0x91, 0xfc, 0x09, 0x7c, 0x13, 0xff, 0xc0, 0x37, 0xa1,
	0xdd, 0xd8, 0x8d, 0x71, 0xdb, 0x53, 0x4f, 0xd6, 0xbc, 0xf7, 0x76, 0xde, 0xf3, 0xec, 0x2c, 0xb8,
	0x5c, 0x44, 0x63, 0x91, 0xa5, 0x2a, 0x25, 0x07, 0x5c, 0x44, 0xc1, 0x09, 0x0c, 0xa6, 0xb9, 0x42,
	0xa6, 0xb2, 0x28, 0xd9, 0x50, 0xfc, 0x79, 0x87, 0x52, 0x91, 0x63, 0x80, 0x3d, 0xe8, 0xdb, 0x43,
	0x7b, 0xd4, 0xa5, 0x15, 0x24, 0xb8, 0x83, 0x7e, 0xf5, 0x90, 0xd8, 0xe6, 0xe4, 0x3d, 0x34, 0x32,
	0x94, 0xc2, 0x88, 0x7b, 0x93, 0xb7, 0x63, 0x6d, 0x53, 0xd3, 0x8c, 0x29, 0x4a, 0x91, 0x26, 0x12,
	0xa9, 0x91, 0x06, 0xef, 0xa0, 0x5d, 0x22, 0xa4, 0x03, 0x2d, 0xb6, 0x3e, 0x3d, 0x9d, 0x33, 0xe6,
	0x59, 0xba, 0x38, 0x0b, 0x17, 0xe7, 0x6b, 0x3a, 0xf7, 0x6c, 0xe2, 0x42, 0x73, 0x4e, 0xe9, 0x8a,
	0x7a, 0x4e, 0xf0, 0xc7, 0x81, 0x01, 0xcb, 0xa5, 0xc2, 0x78, 0x91, 0x7c, 0x4b, 0xcb, 0xb0, 0x43,
	0xe8, 0x5c, 0xa5, 0x8a, 0x6f, 0x97, 0x18, 0xa7, 0x59, 0x6e, 0x02, 0x34, 0x68, 0x15, 0x22, 0x23,
	0xe8, 0x87, 0xbf, 0x78, 0xb4, 0xe5, 0x37, 0x5b, 0x2c, 0x54, 0x8e, 0x51, 0xd5, 0x61, 0xfd, 0xe3,
	0x6b, 0x89, 0xb7, 0x85, 0xe8, 0xc0, 0x88, 0x2a, 0x08, 0x79, 0x03, 0xae, 0x69, 0x3c, 0x8b, 0xe4,
	0x0f, 0xbf, 0x61, 0xe8, 0x3d, 0x40, 0x8e, 0xa0, 0x7d, 0x96, 0x21, 0x1a, 0xb2, 0x69, 0xc8, 0xfb,
	0x5a, 0x73, 0xba, 0x8f, 0xe1, 0x0e, 0x77, 0x5c, 0x59, 0x6b, 0x4e, 0x7f, 0x2f, 0xb9, 0xfa, 0xee,
	0xb7, 0x86, 0xf6, 0xc8, 0xa5, 0xf7, 0xb5, 0xe6, 0x3e, 0xa5, 0x52, 0x25, 0x3c, 0x46, 0xbf, 0xbd,
	0xe3, 0xca, 0x9a, 0xf4, 0xc0, 0x59, 0x31, 0xdf, 0x35, 0xa8, 0xb3, 0x62, 0x26, 0x5d, 0x14, 0xa3,
	0x54, 0x3c, 0x16, 0x3e, 0x14, 0xe9, 0x4a, 0x40, 0x5f, 0x5a, 0x75, 0x78, 0x4f, 0x5d, 0x5a, 0x4d,
	0xf3, 0xec, 0x4b, 0xfb, 0x6d, 0x83, 0xf7, 0x99, 0xad, 0x2e, 0x96, 0x28, 0x25, 0xdf, 0xe0, 0xce,
	0x78, 0xf2, 0x9f, 0xf1, 0xb1, 0x31, 0xae, 0x8b, 0xea, 0xce, 0x61, 0xc5, 0xd9, 0x83, 0x6e, 0xe1,
	0x7c, 0xad, 0x8f, 0x79, 0x16, 0x19, 0xc0, 0x8b, 0xc5, 0xc5, 0x97, 0xf0, 0x7c, 0x31, 0xbb, 0xbe,
	0x0c, 0x29, 0xd3, 0x21, 0x3c, 0xe8, 0x96, 0xd0, 0x2c, 0xbc, 0x0a, 0x3d, 0x67, 0xf2, 0xd7, 0x86,
	0xd6, 0x8c, 0x2b, 0x1e, 0x8a, 0x88, 0x7c, 0x80, 0x0e, 0xc3, 0xe4, 0x56, 0xef, 0xe8, 0x52, 0x6e,
	0xc8, 0xeb, 0x07, 0x1b, 0x6b, 0xb6, 0xeb, 0xe8, 0xe5, 0x63, 0x9b, 0x1c, 0x58, 0xe4, 0x23, 0xf4,
	0xf4, 0xf1, 0xfd, 0xb4, 0x8a, 0x0e, 0x0f, 0xf6, 0xb3, 0xe8, 0x50, 0x1b, 0x6b, 0x60, 0x91, 0x29,
	0xf4, 0x75, 0x87, 0xca, 0x6f, 0x3f, 0x19, 0xe2, 0xd5, 0xa3, 0x03, 0x0a, 0xac, 0x69, 0xf3, 0xab,
	0x7e, 0xc4, 0x37, 0x87, 0xe6, 0x41, 0x9f, 0xfc, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x9b, 0x5f, 0x91,
	0xc1, 0xdd, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DataApiClient is the client API for DataApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DataApiClient interface {
	// Send Byte String
	SendByteMsg(ctx context.Context, in *ByteStringRequest, opts ...grpc.CallOption) (*ByteStringReply, error)
	// Send collected system info.
	SendSystemInfo(ctx context.Context, in *SystemInfoRequest, opts ...grpc.CallOption) (*SystemInfoReply, error)
	// Send JSON Messages.
	SendJSONMessage(ctx context.Context, in *ByteStringRequest, opts ...grpc.CallOption) (*JSONMessageReply, error)
}

type dataApiClient struct {
	cc *grpc.ClientConn
}

func NewDataApiClient(cc *grpc.ClientConn) DataApiClient {
	return &dataApiClient{cc}
}

func (c *dataApiClient) SendByteMsg(ctx context.Context, in *ByteStringRequest, opts ...grpc.CallOption) (*ByteStringReply, error) {
	out := new(ByteStringReply)
	err := c.cc.Invoke(ctx, "/api.DataApi/SendByteMsg", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataApiClient) SendSystemInfo(ctx context.Context, in *SystemInfoRequest, opts ...grpc.CallOption) (*SystemInfoReply, error) {
	out := new(SystemInfoReply)
	err := c.cc.Invoke(ctx, "/api.DataApi/SendSystemInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataApiClient) SendJSONMessage(ctx context.Context, in *ByteStringRequest, opts ...grpc.CallOption) (*JSONMessageReply, error) {
	out := new(JSONMessageReply)
	err := c.cc.Invoke(ctx, "/api.DataApi/SendJSONMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataApiServer is the server API for DataApi service.
type DataApiServer interface {
	// Send Byte String
	SendByteMsg(context.Context, *ByteStringRequest) (*ByteStringReply, error)
	// Send collected system info.
	SendSystemInfo(context.Context, *SystemInfoRequest) (*SystemInfoReply, error)
	// Send JSON Messages.
	SendJSONMessage(context.Context, *ByteStringRequest) (*JSONMessageReply, error)
}

// UnimplementedDataApiServer can be embedded to have forward compatible implementations.
type UnimplementedDataApiServer struct {
}

func (*UnimplementedDataApiServer) SendByteMsg(ctx context.Context, req *ByteStringRequest) (*ByteStringReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendByteMsg not implemented")
}
func (*UnimplementedDataApiServer) SendSystemInfo(ctx context.Context, req *SystemInfoRequest) (*SystemInfoReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendSystemInfo not implemented")
}
func (*UnimplementedDataApiServer) SendJSONMessage(ctx context.Context, req *ByteStringRequest) (*JSONMessageReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendJSONMessage not implemented")
}

func RegisterDataApiServer(s *grpc.Server, srv DataApiServer) {
	s.RegisterService(&_DataApi_serviceDesc, srv)
}

func _DataApi_SendByteMsg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ByteStringRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataApiServer).SendByteMsg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.DataApi/SendByteMsg",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataApiServer).SendByteMsg(ctx, req.(*ByteStringRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataApi_SendSystemInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SystemInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataApiServer).SendSystemInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.DataApi/SendSystemInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataApiServer).SendSystemInfo(ctx, req.(*SystemInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataApi_SendJSONMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ByteStringRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataApiServer).SendJSONMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.DataApi/SendJSONMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataApiServer).SendJSONMessage(ctx, req.(*ByteStringRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DataApi_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.DataApi",
	HandlerType: (*DataApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendByteMsg",
			Handler:    _DataApi_SendByteMsg_Handler,
		},
		{
			MethodName: "SendSystemInfo",
			Handler:    _DataApi_SendSystemInfo_Handler,
		},
		{
			MethodName: "SendJSONMessage",
			Handler:    _DataApi_SendJSONMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
